### ISSUE TITLE
Autoconnect using ~/.lein/repl_port when editing a clojure file outside of a project

### ISSUE THREAD

**Issue by smackesey** [tpope/vim-fireplace#121]
When `lein repl` is run outside of a project, it uses the `user` namespace and creates **~/.lein/repl_port**. I like to write one-off scripts that are outside of any project. It would be nice to have fireplace autoconnect to this "global REPL" when editing a clojure file that is outside of any project.

**Comment by dan-silva** [comment]
Just to note... I had the same problem on my setup, but `fireplace#register_port_file(expand('~/.lein/repl-port'), '/')` made my day :)

**Comment by tpope** [comment]
I think that's a bit too aggressive to bake in, but totally adequate as a configurable solution.
