### ISSUE TITLE
Clojurescript and node

### ISSUE THREAD

**Issue by rburns** [tpope/vim-fireplace#129]
Is connecting to a node backed repl for clojurescript development supported? (I've not yet had luck in getting it to work)

I've tried two approaches:

1) connect to an nrepl from vim-fireplace. the nrepl is run using the method described at the bottom of the page here: https://github.com/bodil/cljs-noderepl Though, using code from this more up-to-date fork: https://github.com/dzacarias/cljs-noderepl The nrepl connection is initiated using :Connect in vim.

This appears to result in clojurescript still being sent to Rhino. any calls into the node environment (eg 'require') fail. Everything else looks to work well.

2) use vim-fireplace Piggieback support. Run a noderepl using 'lein trampoline noderepl'. connect via :Piggieback {env} from within vim. 

Not certain what this results in. I've not been able to suss out the right env to pass in.

**Comment by bhurlow** [comment]
@joakin @rburns have either of you had luck using fireplace + node with the *new* clojurescript repl changes?

**Comment by rburns** [comment]
I've not yet tried it. Would be interested to know any any success you might have.

**Comment by joakin** [comment]
Same as @rburns. I launch and play with figwheel relpls manually, but haven't tried connecting directly.
