### ISSUE TITLE
suggestions for more generalized "eval" mappings

### ISSUE THREAD

**Issue by justinmk** [tpope/vim-fireplace#142]
Regarding https://github.com/tpope/vim-fireplace/issues/116

> I'd actually much rather have something that suggests "eval" or "run" (so that other language plugins can match up the muscle memory), but we don't have a lot of options 

To bring up the quasi-repl, why not `q.`, or some other `q{special char}` variant, in analogy with `q:` and `q/`?

To evaluate the entire buffer, how about `gX`:

```
nnoremap gX :<c-u>%Eval<cr>
```

Instead of `cp{motion}`, consider `gx{motion}`. The default netrw behavior could be reasonably preserved with something like this:

```
nnoremap <expr> gx (synIDattr(synID(line('.'),col('.'),1),'name') =~? 'comment\<bar>string') 
    \ ? "\<Plug>NetrwBrowseX" : "\<Plug>FireplacePrint"
```

**Comment by justinmk** [comment]
@tpope given your recent work on fugitive, fireplace, etc., maybe you're open to a more complete suggestion:

- `yx` instead of `cp` 
    - Alternative: `yr`, mnemonic "Run"
- `g=` instead of `c!` (analogous with vim-scriptease)
    -  `g!` seems more attractive, but I assume there's a reason this was changed in vim-scriptease.
- `gK` instead of `cm`. Rationale: `K` is generally the way to "reveal" things. CTRL-K is also available.
- `q.` instead of `cq` still makes a lot of sense to me. (Analogous to `.` in vim-vinegar.)

**Comment by tpope** [comment]
At 7 years in, I'm loathe to start a bunch of gratuitous experiments. If a convention emerged in other plugins I'd certainly be open to matching it.

I do like `q.`, but it seems like that would make sense as a `cqc` alternative? We could also add a `q(` that behaves similarly to `<C-R>(`.
