### ISSUE TITLE
Not able to work on single file, lein project is always required

### ISSUE THREAD

**Issue by zshamrock** [tpope/vim-fireplace#157]
First of all thank you for your great job on the fireplace, but after the recent changes (it seems you've changed the direction) everything stopped working (see below).

Before I was able to start vim on just one file solution.clj (not a lein project, just one file), and was able to :Connect to repl and do cpp and the rest.
Right now I get: 
    `FileNotFoundException Could not locate     dev/github/languages/clojure/4clojure/106/__init.class or     dev/github/languages/clojure/4clojure/106/.clj on classpath:   clojure.lang.RT.load     (RT.java:443)`

Ok, right now it seems spaces in the path are not accepted any more (but it worked fine before):
`$ pwd`
`~/dev/github/languages/clojure/4clojure/106. Number Maze`

If I remove all the spaces from the path I get the following error:
    `FileNotFoundException Could not locate dev/github/languages/clojure/4clojure/106/NumberMaze/solution__init.class or dev/github/languages/clojure/4clojure/106/NumberMaze/solution.clj on classpath:   clojure.lang.RT.load (RT.java:443)`

Ok, I also need to remove all the dots from the path (again worked fine before):
then if I try to evaluate (cpp) on simple form `(require '[clojure.test :refer [is]])` I get the following error:
    `CompilerException java.lang.RuntimeException: Unable to resolve symbol: require in this context, compiling:(dev/github/languages/clojure/4clojure/106NumberMaze/solution.clj:4:1)`

It seems, you have the hard dependency the current file to be the part of lein project (which is not the case, I just do small kata/code challenges, and don't need full blown lein project, I do TDD directly in the source file where the kata/solution is).

All right, lets create the lein project instead:
if then I try to evaluate (cpp) the same form I get the same error unless I add any namespace on top of it, then it works fine (again hard dependency on lein).

Why it is not possible to work on just one single file outside of the lein project? Considering it worked fine for both of them (lein project and single file) before.

Thank you.

**Comment by tpope** [comment]
I think, given the weird classpath, the `(in-ns)` declaration is an adequate solution, barring better suggestions.
