### ISSUE TITLE
Annoying scratch buffer at the top of the window

### ISSUE THREAD

**Issue by Heliosmaster** [tpope/vim-fireplace#164]
When `lein repl` is connected to my vim instance, i have this annoying behavior:

as soon as I start typing, a scratch buffer pops at the top of the screen, shifting the text (that i am looking for) down a few lines, making the coding troublesome.

Screenshots:

Before autocompletion kicks in:

![before](http://cl.ly/image/3i1w261a1o1g/Image%202014-06-26%20at%2010.54.15%20am.png)

![after](http://cl.ly/image/2e3b1h0M103f/Image%202014-06-26%20at%2010.54.28%20am.png)

I'm not entirely sure this is a wanted behavior, however my knowledge of vim(script) is somewhat limited and i have no idea how to turn it off or change it in any way.

With no repl connected, of course there is no problem, but then a lot of the good gets also thrown away.

For reference, I have yadr installed and vim-fireplace, vim-clojure-static, rainbow-parentheses

**Comment by glts** [comment]
Would you consider adding something like

    autocmd CompleteDone *.clj pclose

to fireplace.vim to close the preview window automatically?

**Comment by tpope** [comment]
That would imply the Clojure completion preview window is somehow more worthy of closing than other languages, which I don't buy.
