### ISSUE TITLE
attempting to connect to a Ritz nREPL

### ISSUE THREAD

**Issue by mascip** [tpope/vim-fireplace#171]
Hi Tim, I'm trying to connect to a Ritz nREPL from Vim, but I don't manage to get `:Connect` to work.
Have you tried to do this? Did you manage to get it to work? 

The main reason I'm trying to do this, is to get the feature "break on exceptions".

Here is what I've tried.

I `:Connect` and give the Ritz nREPL port number, and it displays this error message:

```
Exception in thread "Ritz-reply-msg-pump" java.lang.AssertionError: Assert failed: session
    at ritz.nrepl$process_reply.invoke(nrepl.clj:183)
    at ritz.nrepl$reply_pump$fn__5055.invoke(nrepl.clj:219)
    at ritz.nrepl$reply_pump.invoke(nrepl.clj:209)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:605)
    at clojure.core$partial$fn__4072.doInvoke(core.clj:2345)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:744)
```

which I don't understand. It's happening in Ritz, so perhaps I should ask Hugo Duncan. But neither him nor me know exactly what vim-fireplace is sending to the nREPL, so I thought I'd ask you first if you have any idea.

But first, I've tried a few more things.

I managed to connect to the Ritz nREPL from a REPL by using this code:

```
=> (require '[clojure.tools.nrepl :as repl])
nil
=> (with-open [conn (repl/connect :port 59258)]
     (-> (repl/client conn 1000)    ; message receive timeout required
       (repl/message {:op "eval" :id "anything here" :code "(+ 2 3)"})
       repl/response-values))
=> [5]
```

Note: Ritz requires an `:id` in the message.

Now I'm trying to get the same thing to work with vim-fireplace, so I poked in the source code a bit, in particular in `fireplace#nrepl#for(transport)` in the file autoload/fireplace/nrepl.vim, at this line:

```
let client.session = client.process({'op': 'clone', 'session': 0})['new-session']
```

So I tried to use the `clone` op from a REPL and it seems to work (I don't get any error):

```
=> (require '[clojure.tools.nrepl :as repl])
nil
=> (with-open [conn (repl/connect :port 59258)]
     (-> (repl/client conn 1000)    ; message receive timeout required

       (repl/message {:op "clone"})
       repl/response-values))
```

But if I add `:session 0` in the `repl/message`, then I get this error:

```
ERROR: Unhandled REPL handler exception processing message {:id cfd0704d-b55a-4022-ba22-55602c351b3b, :op clone, :session 0}
```

So I thought that `:session 0` might be the problem in that line of vim-fireplace, and I removed it. But then I get:

```
    Vim(let):E716: Key not present in Dictionary: session
```

Now I've broken vim-fireplace.

Not sure where to go from there.

**Comment by freethejazz** [comment]
I believe Cider has a debugger now, although I may be mistaken as I'm very new to the ecosystem: https://github.com/clojure-emacs/cider#debugging

**Comment by bbatsov** [comment]
Yes, it has. The debugger was added in version 0.9.

On 10 March 2016 at 01:19, Jonathan Freeman <notifications@github.com>
wrote:

> I believe Cider has a debugger now, although I may be mistaken as I'm very
> new to the ecosystem: https://github.com/clojure-emacs/cider#debugging
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tpope/vim-fireplace/issues/171#issuecomment-194561197>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com
