### ISSUE TITLE
Request: Disable specific mappings, or use <unique> to not override

### ISSUE THREAD

**Issue by dhleong** [tpope/vim-fireplace#178]
First of all, thank you for this amazing plugin. I would never have fallen in love with Clojure as I have without it!

My specific situation is this: `lein new app` generates a `core` and a `core-test` namespace for testing it. I love the `cpr` binding when I'm in the test file, but found it's also useful to run the tests when editing the core file. I've bound a function to `cpt` that adds "-test` to `fireplace#ns()` and does `RunTests` on it, but what I'd really like is for `cpr` to "do the right thing" regardless of which file I'm editing. 

I have the function for this as well, now mapped again to `cpt`, but mapping it to `cpr` (easier to type) gets overwritten by fireplace's default. I don't know if this is behavior that you want to be standard, so I'd like to be able to disable *just* `cpr` and keep the rest of the mappings that fireplace makes.

**Comment by tpope** [comment]
As `<unique>` generates an error message on startup, I don't understand why it would help you (or anybody ever, really). For disabling, I'm not willing to go any more granular than "all `c` mappings". If you want to hack up the existing mappings, it's on you to find a way to do that. (Hint: try an autocommand in a `after` directory.)

Personally, my solution to this is the combination of salve.vim, dispatch.vim, and `:nnoremap d<CR> :Dispatch<CR>` (or pick your own map, of course). This gives you a map for running tests that's easily extensible to other languages.
