### ISSUE TITLE
breaking infinite or long-running repl evaluations

### ISSUE THREAD

**Issue by verydapeng** [tpope/vim-fireplace#182]
connected via nrepl (started by lein repl)

(interate inc 0)

:Eval the code above, ctrl-c break the command, however the background evaluation still goes on, CPU usage goes 100%

if we do the same inside lein repl console, CPU will come back normal after hitting ctrl-c

**Comment by jstokes** [comment]
Did this crop back up? I'm on the latest build of vim-fireplace, running 
`(iterate inc 0)`

And trying to Ctrl-C does not interrupt the running process - vim just hangs until I get a OOM.

**Comment by tpope** [comment]
Just tried and it still works for me. I wouldn't be surprised if there was some fiddling platform issue hiding somewhere.

**Comment by jstokes** [comment]
You're right - thanks for checking. A plugin I was using had remaped C-c in normal mode and was catching it. Commenting that line out and I can now stop evaluation.
