### ISSUE TITLE
%Eval produces EOF exception on vim 7.4.537

### ISSUE THREAD

**Issue by wkalt** [tpope/vim-fireplace#190]
I'm running arch linux with vim 7.4.537 and fireplace b999b09. On almost every file, %Eval produces

CompilerException java.lang.RuntimeException: EOF while reading, starting at line 1

with a reference to the open file.

Anecdotally this does not affect project.clj.

**Comment by cedrictools** [comment]
Have seen this error too but not after upgrade to vim 7.4.580, may be solved ?

**Comment by wkalt** [comment]
Yep, looks solved to me.
