### ISSUE TITLE
:Doc error with ClojureScript

### ISSUE THREAD

**Issue by jamienglish** [tpope/vim-fireplace#191]
Whenever I use `:Doc` when connected to a ClojureScript repl I get the following error:
```
CompilerException java.lang.RuntimeException: Unable to resolve symbol: symbol in this context, compiling:(/private/var/folders/cb/tfs9fn9d5cgdk11ws5_6r_mc0000gn/T/form-init41979959
37335747960.clj:1:1)
Error detected while processing function <SNR>62_Doc..fireplace#info..fireplace#evalparse:
line   12:
E605: Exception not caught: Clojure: class clojure.lang.Compiler$CompilerException
```
If I do `:Eval (cljs.repl/doc apply)` then the documentation is printed in my browser console.

**Comment by tpope** [comment]
Do you have cider-nrepl installed? It's a requirement for this operation.

**Comment by jamienglish** [comment]
I hadn't! That fixed it, thanks. I should have read the manual...
