### ISSUE TITLE
Initial :Connect does not result in a usable connection

### ISSUE THREAD

**Issue by clumsyjedi** [tpope/vim-fireplace#192]
I have a project with two running repls.
1. A repl on localhost, started with `lein repl :headless :port 2816`.
2. A repl on a remote host (10.251.76.25:7190)

When I start vim, and issue this command `:Connect nrepl://10.251.76.25:7190` I get 

```
Connected to nrepl://10.251.76.25:7190
Scope connection to: ~/workspace/myprojname
```

Furthermore, using ngrep I can see TCP traffic going out to port 7190 

```
T 10.100.6.39:55554 -> 10.251.76.25:7190 [AP]
d2:id29:fireplace-arkham-1421982576-12:op5:clonee

... lots more data

T 10.251.76.25:7190 -> 10.100.6.39:55556 [AP]
d2:id29:fireplace-arkham-1421982576-37:session36:4a012cbd-7e38-4d39-92928f4f83f98b6a6:statusl4:doneee
```

At this point, any commands I issue in vim, through :Eval or cpp, are evaluated in the local (2816) repl. No network traffic is seen over port 7190 in this case.

If I reconnect to the remote repl using the same :Connect command, then it works. Commands are evaluated in the remote repl, and I can see data being streamed over port 7190 as I issue these commands.

My environment:
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep  9 2014 16:30:51)
OSX Yosemite 10.10
java version "1.7.0_75"
Leiningen 2.4.3 on Java 1.7.0_75 Java HotSpot(TM) 64-Bit Server VM
fireplace: b999b09cd9d69f359fa5668e81b09dcfde455cca

I have rolled back my vim-fireplace versions to see when this behaviour started and it looks like it was in the latest commit. Everything works ok for me with 506cf288bdc698ae61faf064af0093fdcfccc73c.

Additionally, this behaviour does not manifest if I do not run the local repl. In this case the :Connect commands works, and code :Eval'd in fireplace is evaluated on the remote repl.

**Comment by tpope** [comment]
Basically what is happening here is the most recent connection is always used, and the local connection is being established lazily, *after* you've already explicitly connected. One trivial improvement might be to force the local automatic connection to be eager when you first load the file, although you could still get burned if you start repl later. I think ideally, the automatic connection would just always have low priority, but I'm not sure how to get there from where we are now.

**Comment by tpope** [comment]
Should be fixed.
