### ISSUE TITLE
Classpath issues when used with boot

### ISSUE THREAD

**Issue by jgdavey** [tpope/vim-fireplace#194]
I'm using [boot][], and am having trouble with `fireplace#path()` providing expected things.

Without `cider-nrepl` enabled, the classpath returns something fairly nonsensical: `[/usr/local/bin/boot]`. That is, it returns the System's default ClassLoader path. This is best resolved by using `cider-nrepl`.

Adding `cider-nrepl` to the mix, using instructions provided [here](https://github.com/boot-clj/boot/wiki/Cider-REPL), the classpath nrepl middleware returns the correct classpath, and the nrepl client connection receives the expected  The issue is that boot uses tempfiles (copying your project files to temporary directories), so the path of the current buffer is never actually on the classpath proper.

Instead, temporary directories are added to a custom ClassLoader's classpath, which contain your source files (actually, hard-linked to the original files).

So, for example, if I were to have a project with a common Leiningen-like directory structure, with source file at `/Users/josh/project/namespace/file.clj`, the file would actually live, for the purposes of the boot repl, at `/Users/josh/.boot/tmp/Users/josh/project/abc/-p12345/namespace/file.clj`, where `abc` and `-p12345` are randomized components.

Boot is gaining popularity, and I definitely prefer it whenever possible to Leiningen (less memory usage, one JVM, easier to write tasks, etc, etc). I'd love to help deal with this issue. It's preventing some fireplace features from working correctly at the moment.

Thoughts?

[boot]: https://github.com/boot-clj/boot

**Comment by tpope** [comment]
I have more questions than answers. How does it work on Windows? What happens when you create a new file?

**Comment by jgdavey** [comment]
For hardlinks, it uses `java.nio.file.Files.createLink`, which apparently works fine on NTFS systems.
The original source paths are watched for changes (create, modify, delete, etc).

There are a lot of temporary directories set up when using boot. It uses a "immutable filesystem"-like data structure that abstracts over all of these sandboxed directories. The temp dirs are an implementation detail, but one that leaks through in the case of fireplace's `path`, `findresource` and friends.
