### ISSUE TITLE
Switch (remote) repl to namespace of current buffer

### ISSUE THREAD

**Issue by instilled** [tpope/vim-fireplace#196]
Let me first thank you for your great vim libraries. They're a true time saver. 
I've recently switched from Emacs to vi for editing clojure. So far I'm really happy with how vim-fireplace handles things. But there's one thing I'm missing: switching the namespace in the repl to the buffer currently being edited. Thanks!

**Comment by tpope** [comment]
If you mean changing the namespace of your externally running `lein repl` or whatever, I don't think that's possible.

**Comment by instilled** [comment]
That's exactly what I meant. After thinking more about this I do agree this is not possible. Cheers for clarifying.
