### ISSUE TITLE
java.lang.RuntimeException: Unable to resolve symbol: symbol in this context

### ISSUE THREAD

**Issue by andreypopp** [tpope/vim-fireplace#198]
Steps to reproduce:
```
% lein new tenzing your-app +reagent
% cd your-app
% boot dev # terminal 1
% vim src/cljs/your_app/app.cljs # terminal 2
```
Now in vim:
```
:Piggieback (adzerk.boot-cljs-repl/repl-env :port 9000)
```
Open `http://localhost:3000` in a browser. See things like `cpr`, `cqq`, `cqc` work but any attempt to see docs via `:Doc` or omnicompletions results in the error:
```
java.lang.RuntimeException: Unable to resolve symbol: symbol in this context
```

Project isn't a leiningen project so this might be related to #157 but I've seen commits in vim-fireplace related to support for boot and so I think that should work w/o `project.clj`.

**Comment by tpope** [comment]
Do you have cider-nrepl?

**Comment by andreypopp** [comment]
@tpope Nope.

**Comment by tpope** [comment]
Install it.

**Comment by andreypopp** [comment]
Not sure how I missed that step. Sorry for the noise.
