### ISSUE TITLE
Generate help tags

### ISSUE THREAD

**Issue by mpettis** [tpope/vim-fireplace#199]
Upon first install, issuing:
`:help fireplace`
doesn't get me anything.  Then poking around your other repos, I saw this:
`vim -u NONE -c "helptags vim-fugitive/doc" -c q`
When I did:
`vim -u NONE -c "helptags vim-fireplace/doc" -c q`
then
`:help fireplace`
worked.  Consider adding this to the install directions to `vim-fireplace` as well as the other projects for which this works?  Or perhaps this is a known thing that I should do but am too new to vim to have realized...

Thanks for the great plugins.

**Comment by tpope** [comment]
It's not as well known as it should be. I'd merge a pull request to add it to the README.
