### ISSUE TITLE
Neovim support (async)

### ISSUE THREAD

**Issue by Deraen** [tpope/vim-fireplace#202]
Hi,

Has there been any thought about adding [Neovim](https://github.com/neovim/neovim) support to Fireplace? Fireplace already works on Neovim but using Neovim's new plugin architecture would enable async support. I think this might be possible with few `if has('nvim')` tests and separate python files. Though a separate branch or fork would probably be easier at first than trying to support both Vim and Neovim.

Here are a few interesting links:
- [Neovim differeneces](http://neovim.org/doc/user/nvim_intro.html)
- [list of plugins with Neovim support](https://github.com/neovim/neovim/wiki/Related-projects#plugins)
- [nvim-ipy](https://github.com/bfredl/nvim-ipy).

**Comment by tpope** [comment]
I don't personally have time to look into this. I can tell you I designed the APIs with async in mind (`fireplace#message()` takes a callback, for example). My guess is that adding a Neovim driven backend wouldn't be that hard, while making the currently synchronous frontend actually leverage it might be more challenging.

**Comment by zamaterian** [comment]
It could be pretty nice with omnicomple driven async instead of waiting.. especially if the lein repl isn't started up.

**Comment by tpope** [comment]
Does Neovim support async omnicomplete?

**Comment by Deraen** [comment]
I don't think omnifunc supports async (https://github.com/neovim/neovim/issues/396) but seems like it's possible to implement it using RPC and by triggering complete from some autocmds and bindings and finally calling `complete` with the results: https://github.com/Shougo/deoplete.nvim

**Comment by justinmk** [comment]
There's a [clojure RPC client for Neovim](https://github.com/jebberjeb/neovim-client) but it is early stage.

**Comment by michaelbruce** [comment]
Hey,

I'm looking to modify vim-fireplace to use make asynchronous calls to the nrepl.

Looking at the s:nrepl_transport_call in nrepl_connection.vim there are terminators/selectors passed as arguments - this function is called in a very unusual manner on L120 (provided in the snippet below):

```
let s:nrepl_transport = {
      \ 'close': s:function('s:nrepl_transport_close'),
      \ 'command': s:function('s:nrepl_transport_command'),
      \ 'dispatch': s:function('s:nrepl_transport_dispatch'),
      \ 'call': s:function('s:nrepl_transport_call')}
```

Is anybody familiar with the interface for the nrepl or knows where an api reference might be?

At the moment I'm trying to get a simple call using the python function like so:
`dispatch("127.0.0.1", 9999, noop, None, "call", "(+ 40 2)", ['done'], {'id': 'mvp-test'})`

**Comment by tidux** [comment]
Vim now has async as of 8.1, so it's not just for neovim anymore.

**Comment by tpope** [comment]
Fireplace now uses jobs and supports asynchronous nREPL messaging. Asynchronous omnicomplete appears to be involved enough to require a third party plugin. @SevereOverfl0w is evaluating options.
