### ISSUE TITLE
Eval selection in comments does not return correct value

### ISSUE THREAD

**Issue by kindlychung** [tpope/vim-fireplace#203]
For example, I have a line like this:

    ;; (mod 5 3)

I select just the `(mod 5 3)` part, then `:Eval`, the returned value is `<namespace...>` instead of 2. When I remove the `;;` at the beginning of the line, then the result is correct.

**Comment by tpope** [comment]
`:Eval`, like all ex commands, is linewise only. If you use `cpp` it will work as expected.

**Comment by kindlychung** [comment]
With cpp I got something like this:

    Error detected while processing function <SNR>41_printop..<SNR>41_opfunc:
    line   21:
    E20: Mark not set
    E20: Mark not set

**Comment by tpope** [comment]
Oh, that's because it doesn't know how to parse a sexp out of a comment. Generally, using either `#_(...)` or `(comment ...)` is more idiomatic for this sort of stuff.

**Comment by kindlychung** [comment]
I am thinking, maybe we can work around this by creating a function that copies the form and then passes the string to :Eval. 

This is useful because one can run examples in documentations quite easily.
