### ISSUE TITLE
Clojure 1.7 and .cljc file support

### ISSUE THREAD

**Issue by brandonbloom** [tpope/vim-fireplace#206]
I'm not quite sure what's involved, but didn't see any explicit mention of this in the source or existing tickets.

**Comment by tpope** [comment]
I'm not sure either, but I've extended the limited support for the `.cljx` to the `.cljc` extension.

**Comment by spacepluk** [comment]
It seems to be working fine for me, except that I can't evaluate stuff in cljc files through piggieback/figwheel.

**Comment by tpope** [comment]
Yeah, and that's really just a limitation of the current UI. I think this is done.
