### ISSUE TITLE
Doesn't read private functions

### ISSUE THREAD

**Issue by jarofghosts** [tpope/vim-fireplace#207]
This plugin is great, but none of the features (docs, source, or jump-to) seem to work on functions defined via `defn-`.

**Comment by tpope** [comment]
wfm. You're trying on functions within the same namespace?

**Comment by jarofghosts** [comment]
Here is a short demonstration:

![vim-fireplace](https://cloud.githubusercontent.com/assets/1013892/7551847/80156126-f64c-11e4-8632-8334107b4208.gif)

Notice in the beginning I attempt to doc `html` and then view its source, and it is defined right above. I then demonstrate that those do work with builtins and other functions defined in the same namespace.

**Comment by tpope** [comment]
Try both with and without cider-nrepl.

**Comment by jarofghosts** [comment]
Ah, yep, cider-nrepl wasn't working. Didn't notice since everything else seemed to work so well. Works now, thanks!

**Comment by tpope** [comment]
Going to assume this was a cider-nrepl bug, unless someone says otherwise.
