### ISSUE TITLE
Test fails but 0 failures

### ISSUE THREAD

**Issue by rogergl** [tpope/vim-fireplace#208]
RunTests gives the following output:

| Testing hw.core-test
test/hw/core_test.clj|5 warning| a-test
|| FIXME, I fail.
|| expected: (= 0 1)
||   actual: (not (= 0 1))
|| 
|| Ran 1 tests containing 0 assertions.
|| 0 failures, 0 errors

Running lein test from the command line produces the expected result.

**Comment by rogergl** [comment]
Now I tried the following in the repl

 (clojure.test/run-tests 'hw.core-test)

which gives:

    Testing hw.core-test
 
    FAIL in (a-test) (core_test.clj:7)
    FIXME, I fail.
    expected: (= 12 1)
    actual: (not (= 12 1))

    Ran 1 tests containing 1 assertions.
    1 failures, 0 errors.
    {:type :summary, :fail 1, :error 0, :pass 0, :test 1}

but running "RunTests ' hw.core-test" in Vim gives:

     5 || FIXME, I fail.
     4 || expected: (= 12 1)
     3 ||   actual: (not (= 12 1))
     2 ||.
     1 || Ran 1 tests containing 0 assertions.
     8   || 0 failures, 0 errors.

**Comment by tpope** [comment]
Confirmed. It's probably a bug somewhere in https://github.com/tpope/vim-fireplace/blob/819438bdf438ce3d4a18d1562a19aa63c5efeb63/plugin/fireplace.vim#L1455-1471

**Comment by rogergl** [comment]
Yes the problem seems to be this call

    ((.getRawRoot #'clojure.test/report) m)))

since m is not modified if a test fails.

**Comment by rogergl** [comment]
Maybe this fix:

    (clojure.test/with-test-out
                              (clojure.test/inc-report-counter (:type m)) ;; << added
                               (println (clojure.string/join "\t" [file line (name (:type m)) test]))
                               .....

**Comment by tpope** [comment]
If you can confirm it works and wrap it in a pull request I will merge.

**Comment by rogergl** [comment]
Output before change:

    Documents/hw/test/hw/core_test.clj|5 warning| a-test
    || FIXME, I fail 2
    || expected: (= 12 1)
    ||   actual: (not (= 12 1))
    || 
    || Ran 1 tests containing 1 assertions.
    || 0 failures, 0 errors

output after change

    | FIXME, I fail 2
    || expected: (= 12 1)
    ||   actual: (not (= 12 1))
    || 
    || Ran 1 tests containing 2 assertions.
    || 1 failures, 0 errors
