### ISSUE TITLE
No OmniComplete for symbols form other namespace

### ISSUE THREAD

**Issue by rogergl** [tpope/vim-fireplace#209]
Given 
 
    (ns hw.test)
       (def t 10)
        (defn hallo [] 3)

When I require this namespace like this

    (ns hw.core
      (:require [hw.test :as tt]))

Then I do not get any code completion for symbols from hw.test if I'm in the hw.core file. 

Is this expected ?

**Comment by tpope** [comment]
Should work fine if you absolutely qualify them.

**Comment by rogergl** [comment]
After more digging I realized that YouCompleteMe is the problem here.
