### ISSUE TITLE
Support for completion context

### ISSUE THREAD

**Issue by Deraen** [tpope/vim-fireplace#212]
Complete operation can be passed context option so that the completion library can give better suggestions. The context should be the surrounding toplevel form with word being completed replaced with word `__prefix__`.

I did already start with this: https://github.com/tpope/vim-fireplace/compare/master...Deraen:completion-context?expand=1
I have the toplevel form yanked to variable but I'm not sure how I can insert the `__prefix__` in correct position. Maybe some magic using current cursor position?
Looks like the yanked string doesn't contain the word being completed.

- complete operation docs: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/complete.clj#L63
- compliment context docs: https://github.com/alexander-yakushev/compliment/wiki/Context

**Comment by tpope** [comment]
There's not going to be easy trick. You'll likely have to use some combination of functions like `match()` and `matchend()`, checking the position of the marks you yanked from, and stitching together substrings.
