### ISSUE TITLE
Disable default key mappings

### ISSUE THREAD

**Issue by dubiousdavid** [tpope/vim-fireplace#216]
It would seem that adding `let g:fireplace_no_maps=1` to my .vimrc file would disable the default key mappings, but that doesn't seem to work. Is there a way to do this?

**Comment by tpope** [comment]
Works for me.

**Comment by dubiousdavid** [comment]
My mistake. I didn't realize there were existing mappings to `K` and `[d`. I understand why you chose them now :)
