### ISSUE TITLE
get_complete_context can be very slow

### ISSUE THREAD

**Issue by aaronjensen** [tpope/vim-fireplace#218]
In a fairly large clojure file (254 lines):

https://gist.github.com/aaronjensen/28a14a2e07bf7c70b379#file-gistfile1-txt-L1217

maybe related: 

http://vim.1045645.n5.nabble.com/Extremely-extremely-slow-paren-matching-td1197698.html
https://groups.google.com/forum/#!topic/comp.editors/ntLth8dH10g
https://groups.google.com/forum/#!searchin/vim_dev/searchpairpos/vim_dev/xQ9dYHdc1ko/iQxwhsErYpYJ

Consider including a setting for timeout, it takes ~35 nested parens to blow a 25ms timeout. Tbh it's a little wild that it takes vim so long to do this...

**Comment by Deraen** [comment]
Interesting. I haven't noticed it being slow even on larger files, though it should be mostly number of nested parentheses that matter. Could you provide some example file so I could test this?

Timeout could be good idea anyway.

**Comment by aaronjensen** [comment]
I don't remember the exact file, this was a while ago, but I believe that just having a massive number of nested parens on their own: `((((((((((((((((((((((((())))))))))))))))))))))` type of thing blows it up

**Comment by tpope** [comment]
Writing this off as irreproducible for now. Will investigate further if an example is provided.
