### ISSUE TITLE
can fireplace reutilize buffer numbers ?

### ISSUE THREAD

**Issue by geraldodev** [tpope/vim-fireplace#219]
Can fireplace reutilize buffer numbers ?

I've started to use :ls and map switch buffers with :b1 :b2 ...
Suddenly new buffers was after 100. 
I use cpr and K a lot.

**Comment by tpope** [comment]
No, Vim does not allow for reusing buffer numbers.

**Comment by geraldodev** [comment]
Thank you very much Mr. Pope

2015-05-25 15:03 GMT-03:00 Tim Pope <notifications@github.com>:
