### ISSUE TITLE
Vim Test plugin is slow when integrating with Fireplace

### ISSUE THREAD

**Issue by leebrooks0** [tpope/vim-fireplace#223]
I have been using this fantastic plugin https://github.com/janko-m/vim-test for Python, and now I am trying to get it to work with Clojure. The idea is that it lets you run your tests through Fireplace so it is nice and fast (I am aware that Fireplace has some support for running tests, but Vim Test gives finer grained control e.g. I can run just one test).

The problem is that the results are taking too long to come back indicating some issue of sorts.

The author of the plugin is a not a Clojure dev, and was still awesome to add support for Clojure, but unfortunately he doesn't know what the issue is. I am still very green with vim script and Clojure, and I don't know what the problem is either, the code looks correct to me, and my attempts to diagnose the problem got nowhere.

I reported the issue here https://github.com/janko-m/vim-test/issues/38 originally.

I am hoping someone can take a look and see where the issue is, the Clojure support is only a couple of lines of code...

**Comment by tpope** [comment]
I'm not going to try to understand what vim-test is doing, but I can tell you I don't think it would be *that* hard to make `:.RunTests` run the current test under the cursor, and then vim-test could use that rather than rolling its own solution.

**Comment by leebrooks0** [comment]
That seems like a good idea, maybe `:RunNearestTest`.
Another thing that would be awesome would be `:RunLastTest(s)`, so that you can run your tests repeatedly without having to be in the test file, e.g. when doing TDD and you are busy doing the implementation, whilst running its test repeatedly until it passes without having to navigate back and forth between test and implementation

**Comment by tpope** [comment]
Okay, `:.RunTests` is live. It's on you to pursue getting it supported in vim-test.

I think workflow stuff like `:RunLastTest` belongs in a separate plugin. Personally I use dispatch.vim with `:FocusDispatch`.

**Comment by janko-m** [comment]
This is awesome! I could now greatly simplify my implementation (https://github.com/janko-m/vim-test/commit/26171aee2d2fec4b5868ed92dc033788b4f56152), and use only the high-level Fireplace.vim's commands.
Thank you! :heart:
