### ISSUE TITLE
Post connect hook

### ISSUE THREAD

**Issue by Deraen** [tpope/vim-fireplace#224]
Refactor-nrepl has a configure operation which I would like to call when the connection is established. https://github.com/clojure-emacs/refactor-nrepl#configure

Is there a existing hook for this? I see PreConnect autocmd but not PostConnect.

If there is nothing which allows this and this sounds like a good idea, I can send a PR.

**Comment by Deraen** [comment]
I went around this by calling configure operation once for each buffer when using refactor-nrepl operations (https://github.com/Deraen/vim-cider/blob/978b5575066f09666a6333d27b8b701ac5337965/plugin/cider.vim#L111-L116). I'm still thinking it would be cleaner to do this per connection but after testing few things I couldn't figure how I should do that.

**Comment by tpope** [comment]
So PreConnect is a bit of a misnomer. It's called every single time the connection is *used*, so that, for example, a fresh port can be retrieved from `.nrepl-port`. I think what you want would to hook into would be session creation? That happens in `fireplace#nrepl#for()`.

**Comment by Deraen** [comment]
Yes, `fireplace#nrepl#for()` is what I thought would be a good place but if I want to call `fireplace#message` in the hook it will cause an loop, maybe because the connection is saved to `s:repl_paths` afterwards.

I tried hooking to `register_connection` as that should be called only(?) after connection is added to `s:repl_paths`. It works but it seems to be called twice.

**Comment by tpope** [comment]
You can't use `fireplace#message()`; there's no guarantee is will act on the connection you want. You'll want to temporarily assign the connection to a global variable and act on it directly.

**Comment by Deraen** [comment]
I solved this calling `configure` before each operation which used it. Since then refactor-nrepl has removed `configuration` option and all the operations take options as parameter.

So I don't need this anymore.
