### ISSUE TITLE
fireplace#omnicomplete does not complete from java classes

### ISSUE THREAD

**Issue by mschulkind** [tpope/vim-fireplace#230]
Currently the omnifunc considers 3 sources for completions: namespaces, interned symbols in the current namespace, and public exports from the namespace preceding a '/'. The problem is java classes are none of these. `lein repl` has no trouble autocompleting these, so it should be possible without too much effort. For instance, try triggering the omnifunc after `(String/` in vim and in the repl to see the difference.

**Comment by tpope** [comment]
cc @Deraen

**Comment by Deraen** [comment]
@mschulkind Do you have [cider-nrepl](https://github.com/clojure-emacs/cider-nrepl) installed? I think completion provided by it should provide this.

As for "fallback" completion which is completely implemented inline in Fireplace, yes, it would be possible to add this, but I'm not sure if it would be worth the complexity.

Leiningen/REPL-y uses Clojure-complete for autocompletion but I not sure if it would be wise to depend on that. E.g. is it available if running nRepl server in production app (uberjar)?

**Comment by mschulkind** [comment]
Yes, I have cider-nrepl installed. I also just upgraded to the latest version with no change. Does this work for you?

I agree that relying on deps is a bad idea for reasons you point out.

It seems like this would not be hard to add at all. Here's what Leinengen uses:
https://github.com/ninjudd/clojure-complete/blob/master/src/complete/core.clj

This essentially does almost exactly what fireplace is already doing, but they additionally check java methods with ns-java-methods.

**Comment by Deraen** [comment]
Yes, it works for me.
![](https://www.dropbox.com/s/fhsdtlio86wx7vy/Screenshot%20from%202015-07-22%2019%3A08%3A43.png?dl=1)

Clojure-complete doesn't provide any metadata. Cider-nrepl uses compliment and cljs-complete instead: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/complete.clj

**Comment by mschulkind** [comment]
Hmm. Looks like I've got some digging to do. I've got 2 different computers that both did not work in this case, so I figured it was something that fireplace didn't support. One computer had an up to date fireplace, and the other an old version from Dec. Now that I updated the out of date one, I can complete `String/`, even calling `:echo fireplace#omnicomplete(0, "String/")` directly. The one that was already up to date still isn't working, so time to dig and find out what strange thing is going on.

**Comment by mschulkind** [comment]
I'm gonna close this issue. Thanks for the help. At this point I feel like I'm just going crazy, but at least I know where to look now. Completion suddenly works on both computers now.

**Comment by aleksandersumowski** [comment]
@mschulkind did you ever work out what was the issue? I'm getting "No namespace: KafkaConfig found" after calling `:echo fireplace#omnicomplete(0, "KafkaConfig/")` even though autocompletion works in `lein repl`

**Comment by aleksandersumowski** [comment]
I didn't have cider-repl included ...

**Comment by hs-matt** [comment]
No, I just solved my problem by no longer writing Java or Clojure code :)
