### ISSUE TITLE
Clojurescript Stacktraces

### ISSUE THREAD

**Issue by jebberjeb** [tpope/vim-fireplace#233]
Should .-stack be used rather than .getStackTrace for Clojurescript?

https://github.com/tpope/vim-fireplace/blob/master/autoload/fireplace/nrepl.vim#L190

**Comment by jebberjeb** [comment]
I mean, something simply along the lines of:

```
  if fnamemodify(bufname('%'), ':e') ==# 'cljs'
    let efn = '.-stack'
  else
    let efn = '.getStackTrace'
  endif
  let format_st = '(symbol (str "\n\b" (apply str (interleave (repeat "\n") (map str (' . efn . ' *e)))) "\n\b\n"))'
```

**Comment by tpope** [comment]
Yeah probably, but unfortunately that conditional is inadequate, as it is quite possible to evaluate Clojure while in a ClojureScript file or vice versa.

Does cider-nrepl not have a stacktrace operator for ClojureScript?

**Comment by jebberjeb** [comment]
Looks like they do. I could try to use that -- new territory for me though.

**Comment by jebberjeb** [comment]
Hrm, looks like no?

https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/stacktrace.clj#L147

**Comment by jebberjeb** [comment]
Or, am I misunderstanding something? I'm unable to get stacktraces back from cpp'ing Clojurescript. I must be missing something.

**Comment by tpope** [comment]
There is no built-in support. The fact cider doesn't have it strongly suggests it's not going to be easy to implement. But please do investigate further.

**Comment by tpope** [comment]
As of right now, `.-stack` is in place, and ClojureScript stacktraces are successfully retrieved. However, there's no source map or parsing support, so they're not very useful. I might end up ripping them out and going full on `stacktrace` op.
