### ISSUE TITLE
Error on Connect

### ISSUE THREAD

**Issue by zshamrock** [tpope/vim-fireplace#234]
When trying to connect, I get the following stacktrace in my `lein repl` window:

ERROR: Unhandled REPL handler exception processing message {:id fireplace-debian-1439061958-4, :session e5f3d853-dab8-4c30-bcbe-dcc39d12d80c, :op classpath}
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "s/"

Using nrepl-cider 0.9.1

**Comment by tpope** [comment]
Sounds like an issue with the middleware to me. Anything weird with your class path that might set off an error like that?

**Comment by zshamrock** [comment]
Hi, @tpope, I've created a ticket on cider-nrepl as well https://github.com/clojure-emacs/cider-nrepl/issues/243 with CLASSPATH and other environment settings filled there. As I can see everything looks normal.

**Comment by bbatsov** [comment]
This middleware is trivial, so I'm guessing something's off with your classpath. Although `s/` looks pretty normal to me.

**Comment by tpope** [comment]
Check `(System/getProperty "java.class.path")` to get the full class path.

**Comment by zshamrock** [comment]
```
user=> (System/getProperty "java.class.path")
"/home/alex/tools/aspectj/aspectj-1.7/lib/aspectjrt.jar:/home/alex/tools/clojure/clojure-1.7.0/clojure-1.7.0.jar:.:/home/alex/.lein/self-installs/leiningen-2.5.1-standalone.jar"
```
It looks good.

**Comment by tpope** [comment]
Guessing the fix at clojure-emacs/cider-nrepl#243 will take care of it.

**Comment by zshamrock** [comment]
Yes, correct, have just tried the SNAPSHOT version, and it works.

Although when trying to evaluate `cpp`, get the following `Vim(python):Traceback (most recent call last):`. Any idea on this one?

**Comment by tpope** [comment]
That's a weirdly truncated error. You can change https://github.com/tpope/vim-fireplace/blob/b3b54b87159e110a67f4dd6a97c5581f4cfb4a9f/python/nrepl_fireplace.py#L128 to try to get further info out of it. Open a separate issue for further discussion.
