### ISSUE TITLE
gf doesn't support prefix lists

### ISSUE THREAD

**Issue by msassak** [tpope/vim-fireplace#237]
`require` and `use` support [prefix lists](http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/require) to avoid the need to type common prefixes over and over. For example, in:

```clojure
(ns my.clojure
  (:require [my.clojure.core :as core]
            (my.clojure.x foo
                          [bar :as b]
                          [baz :refer [qux]])))
```

The `foo`, `bar` and `baz` namespaces are underneath `my.clojure.x`, but `gf` can't find them, outputting `Can't find file "foo" in path` instead. Is there a way to get fireplace to recognize these namespaces correctly? (Maybe something in the projections file?)

**Comment by Deraen** [comment]
Are you sure this is caused by prefix lists? I tried following and it sill worked:

```clj
(ns ring.swagger.json-schema-test
  (:require (schema
              [core :as s]
              [coerce :as sc])))

; gf works for these:
schema.core
s/Any
sc/set-matcher
```

**Comment by tpope** [comment]
He's referring to `gf` in the require list itself, which would all but require parsing the entire `:require` declaration to figure out. Would occasionally be handy but not likely to happen.

**Comment by msassak** [comment]
That's right. I figured it might be a PITA to implement, but it never hurts to ask. Thanks!
