### ISSUE TITLE
":help fireplace" not working

### ISSUE THREAD

**Issue by irstevenson** [tpope/vim-fireplace#240]
It would appear that the help file is not working. In your doco you give the instruction to:

    :help fireplace

however when I do that, vim reports:

    E149: Sorry, no help for fireplace

but fireplace is listed in the 'LOCAL ADDITIONS' section of the vim `:help`

```
LOCAL ADDITIONS:				*local-additions*
ctrlp.txt       Fuzzy file, buffer, mru, tag, ... finder. v1.79
EasyGrep.txt
NERD_tree.txt   A tree explorer plugin that owns your momma!
fireplace.txt  Clojure REPL support
```

I have installed fireplace via pathogen - as I have for the other three listed above (for which all have their help working).

I'm seeing this on both OS X and Windows 7.

**Comment by tpope** [comment]
Regenerate your help tags
