### ISSUE TITLE
pipe eval output into separate buffer

### ISSUE THREAD

**Issue by mgrabmair** [tpope/vim-fireplace#242]
I am not a Vim Maven but maybe someone can help me here. I am using Fireplace extensively but find myself in situations where I evaluate something which then disappears on a Keypress and then I work on my code and have to evaluate it again because I forgot some part of it. For example, I bring up the doc of a function but half way through it I forget the order of the last two arguments. Also, I do a lot of Regex work for document cleaning and it would help me if I had the output of the Eval in a dedicated small buffer.

I am not asking for a full repl, but is there an elegant way to pipe the Eval output into another open vim buffer instead of showing it in the main one and having it disappear on a key press?

EDIT:

Ok, I found this: https://github.com/tpope/vim-fireplace/issues/7

:Last works so far. Has someone come up with a way to make it capture future output? Also, can I turn of the auto focus somehow?

**Comment by tpope** [comment]
Adding a `!` preserves focus in the existing window.

**Comment by mgrabmair** [comment]
Great, thanks! This will make for a good working setup for now.

**Comment by tpope** [comment]
No. I do think the `:Last` window should auto-update but not sure how easy it would be to implement.
