### ISSUE TITLE
Always evaluate in a namespace

### ISSUE THREAD

**Issue by SevereOverfl0w** [tpope/vim-fireplace#244]
Is there a way I can :Eval in a particular namespace?

In my situation, I am doing something similar to https://github.com/tpope/vim-fireplace/issues/149 but after an error, it is impossible to run anything outside the broken namespace.

If I switch to a file which is okay (basically it doesn't have any dependencies on my project) it's okay, and I can reload. `project.clj` also has this behavior, as it defaults execution to the user namespace (which is the namespace I want to run :Eval in)

i.e. is there any way for me to always trigger the behavior of :Eval as if it was in project.clj?

**Comment by SevereOverfl0w** [comment]
If I `:call fireplace#echo_session_eval('(go)', {'ns': 'user'})` I can get it to work.

This can probably be closed now, unless there's something you can add @tpope?

**Comment by tpope** [comment]
`:Require` doesn't fix it?

**Comment by SevereOverfl0w** [comment]
Not until I correct the namespace(s) I've broken.

**Comment by tpope** [comment]
Then no, nothing else to add, if you are content with your workaround.
