### ISSUE TITLE
java.io.FileNotFoundException: Could not locate marketing/core__init.class or marketing/core.clj on classpath.

### ISSUE THREAD

**Issue by zshamrock** [tpope/vim-fireplace#245]
Just do some experiment, cpp fails with the error above.

`:echo fireplace#path()` returns among other values `/home/<path>/src`, and inside `src` there is `marketing/core.clj` file.

Is it fireplace issue, or cider issue or my project setup (I used standard `lein new default marketing`).

Use clojure 1.7.0 and cider-nrepl 0.9.1.

**Comment by tpope** [comment]
Does `(require 'marketing.core)` work in the repl?

**Comment by zshamrock** [comment]
No, it fails with the same error. The only way it works for me, if before `:Connect` from vim, I do `(in-ns 'marketing.core)` from repl, which I don't if it is something you have to do?

**Comment by tpope** [comment]
If you can't require the file outside of Vim that's an issue with your setup.
