### ISSUE TITLE
bencode spec requires sorted dicts

### ISSUE THREAD

**Issue by sjl** [tpope/vim-fireplace#248]
The bencode spec [says](https://wiki.theory.org/BitTorrentSpecification#Dictionaries) that dictionary keys must be in sorted order.  Fireplace currently [doesn't sort them](https://github.com/tpope/vim-fireplace/blob/master/autoload/fireplace/nrepl_connection.vim#L24).

**Comment by tpope** [comment]
Was this causing issues, out of curiosity, or just an observation?

**Comment by sjl** [comment]
Only minor ones (once I figured out what was going on): cl-bencode [screams at you](https://github.com/nja/cl-bencode/blob/master/decode.lisp#L155) if the keys are out of order (you can silence it if needed though).
