### ISSUE TITLE
Use Cider's new print-methods

### ISSUE THREAD

**Issue by Deraen** [tpope/vim-fireplace#250]
The new Cider 0.10 has a new `cider.nrepl.print-methods` namespace which implements nice print-method for few classes:

``` clj
(defmulti foo :type)
(defmethod foo :bar [_] 5)
; Now: #object[clojure.lang.MultiFn 0x4bc63181 "clojure.lang.MultiFn@4bc63181"]
; With print-methods: #multifn[foo 0x4bc63181]
(fn foo [x] x)
; Now: #object[clj_suomi.parsers.fixed_length_text$eval19955$foo__19956 0x58564350 "clj_suomi.parsers.fixed_length_text$eval19955$foo__19956@58564350"]
; With print-methods: #function[clj-suomi.parsers.fixed-length-text/eval20005$foo--20006]
(find-ns 'clojure.core)
; Now: #object[clojure.lang.Namespace 0x2880df0 "clojure.core"]
; With print-methods: #namespace[clojure.core]
```

Currently this namespace has to be required somewhere to enable this. Not sure if this should be left to the user (and documented somewhere) or done by Fireplace. One place where Fireplace could require the namespace is `register_connection`.

**Comment by Deraen** [comment]
This will probably be handled by cider-nrepl in next release: https://github.com/clojure-emacs/cider-nrepl/commit/e275f6b902513ea05186a2864d6e7fd66496f7dd

**Comment by Deraen** [comment]
^ if Fireplace requires the version ns somewhere, which I'm not sure about.

**Comment by tpope** [comment]
We should probably just do what Cider itself ends up doing?

**Comment by Deraen** [comment]
Cider is now requiring the print-methods namespace in connection initialization: https://github.com/clojure-emacs/cider/commit/7cc4a192323ef0911c150e6150d3bbd319253342

**Comment by Deraen** [comment]
Cider-nrepl requires these automatically nowadays.

But they aren't usually used with Fireplace as we use fipp for pprinting the results, and print-methods only affect `print`, `pr-str` and `clojure.pprint`. https://github.com/clojure-emacs/cider/issues/1505

Anyway, I think this can be closed as the print-methods are getting loaded.
