### ISSUE TITLE
Make :Connect a bit easier

### ISSUE THREAD

**Issue by rosejn** [tpope/vim-fireplace#252]
Just an idea for making it easier to use vim-fireplace across projects.  Often you have a repl open (now in neovim, hurray!) inside a primary project, but then files open in one or more other libraries that are in the checkouts directory.  In order to evaluate code in these files you have to manually connect, figure out the port number, etc.  How about in the initial :Connect menu that asks about nrepl also showing existing repl sessions from other open files as options for auto-connecting without having to lookup the port?  That way you could easily connect up a variety of files to your currently active repl sessions.

Thanks for vim-fireplace!

**Comment by tpope** [comment]
Fireplace bends over backwards to find the right repl for you, consulting not just the project root but also the class path. Do "checkouts" appear in the classpath?
