### ISSUE TITLE
Socket Server REPL Compatibility

### ISSUE THREAD

**Issue by kul** [tpope/vim-fireplace#253]
With the new inbuild [repl](http://dev.clojure.org/display/design/Socket+Server+REPL) coming in clojure 1.8.0, fireplace `:Connect nrepl://localhost:5555` 
gives `nREPL Connection Error: unexpected type uin bencode data`.

REPL was started with `-Dclojure.server.repl="{:port 5555 :accept clojure.core.server/repl}"`

**Comment by Deraen** [comment]
Obviously trying to connect to Socket REPL server using `nrepl` protocol is not going to work.

Fireplace is built to allow adding support for new protocols, by adding `autpload/fireplace/socketrepl_connection.vim` and some other files. Then one could connect to a socket repl server using command like `:Connect socketrepl://localhost:5555` (note the protocol). The socket repl connection is not too hard to implement.

The hard part is that in the Socket REPL the input and output are not really connected. You write some commands into the connection and get a stream of output. It is not easy to connect one line of output with the evaluation that caused it. Until a solution to this is found, it will be hard to add Socket REPL support to Fireplace.

There is another simple Socket REPL client Vim though: https://github.com/jebberjeb/clojure-socketrepl.nvim

**Comment by tpope** [comment]
At this point, Fireplace is pretty tightly coupled to nREPL style messaging and somewhat coupled to cider-nrepl in particular. I don't think supporting a protocol that only offers bare eval functionality will be feasible.

The new method for adding a custom protocol is to set `let g:fireplace_argv_whatever = ['some-command']`, where `some-command` streams JSON in a manner equivalent to the included script.
