### ISSUE TITLE
Piggieback support using the nodejs repl env doesn't work with (println)

### ISSUE THREAD

**Issue by bhurlow** [tpope/vim-fireplace#255]
given a regular repl setup, when I connect to piggieback using the rhino env like this `:Piggieback (cljs.repl.rhino/repl-env)` `(println)` calls work fine.

Instead with the node.js env: `:Piggieback  (cljs.repl.node/repl-env)` I don't see the results of `(println)` statements. Other evaluation with the node env works just fine.

Any ideas why this might be happening in one env and not the other? Perhaps there's a dynamic var that needs to be bound?

**Comment by bhurlow** [comment]
maybe related?? https://github.com/cemerick/piggieback/blob/master/src/cemerick/piggieback.clj#L165-L167

**Comment by jiangts** [comment]
any updates on this?

**Comment by tpope** [comment]
I'm now getting `java.io.IOException: Stream closed`. I think it's just trying to write to the terminal. I'm not sure there's anything Fireplace can do.
