### ISSUE TITLE
Every clojure exception shows `E716: Key not present in Dictionary`

### ISSUE THREAD

**Issue by danielbraun** [tpope/vim-fireplace#256]
Using Clojure (not cljs) I can connect to nrepl just fine.
I evaluate forms successfully, and see the returned value.

However, on any clojure error I'm getting the same Vimscript error whatsoever. For example:

    (+ 1 1)
    2

    (/ 5 0)
    Vim(return):E716: Key not present in Dictionary: method."(".v:val.file.":".v:val.line.")"

How do I go about debugging this? I can't even see a Vimscript stack trace.

**Comment by danielbraun** [comment]
OK, I figured it's related to: 
https://github.com/tpope/vim-fireplace/blob/df563ed15fa685ce2508bf16b3ca7e176b2e95d3/autoload/fireplace/nrepl.vim#L187

**Comment by tpope** [comment]
It likely boils down to an unsupported cider-nrepl version. Either you need to upgrade or the code needs to be updated.

**Comment by danielbraun** [comment]
Yeah, I managed to solve it.
It was a parsing problem - the `stacktrace` var inside `s:extract_last_stacktrace` should be further unwrapped:

    if a:nrepl.has_op('stacktrace')                                                                                                    
      let stacktrace = filter(a:nrepl.message({'op': 'stacktrace', 'session': a:session}), 'has_key(v:val, "file")')                   
      let fixed_stacktrace = get(stacktrace[0], "stacktrace")                                                                          
      if !empty(fixed_stacktrace)                                                                                                      
          return map(fixed_stacktrace, 'v:val.class.".".v:val.method."(".v:val.file.":".v:val.line.")"')                               
      endif                                                                                                                            
    endif

Like you said, it's most likely an outdated CIDER nREPL.
Oh well, at least I learned about Vimscript, nrepl and CIDER along the way...

Hope this issue helps others possibly facing this issue.
Thanks for your work.

**Comment by glittershark** [comment]
I'm running cider-nrepl 0.12.0-SNAPSHOT (bleeding edge) and this is happening to me still

**Comment by geraldodev** [comment]
I was having this error, but it had to do with a  namespace (ns xyz) not matching the file name. A require on the namespace has showed  the problem. Fixing the namespace the fixed the problem.
