### ISSUE TITLE
Inline Documentation

### ISSUE THREAD

**Issue by ccorcos** [tpope/vim-fireplace#257]
So I'm new to both Vim and Clojure so I don't really know what I'm doing, but I'm playing with Overtone, and I'd love to get inline styles like this:

![image](https://cloud.githubusercontent.com/assets/1794527/12503845/fac16806-c08c-11e5-9a44-7668ed423184.png)

Any ideas?

**Comment by tpope** [comment]
`set completeopt+=preview`

**Comment by ccorcos** [comment]
Hmm. thats not doing anything for me.

I have the repl running, and I can make sounds.

When I type `(sin-os` nothing pops up. If I hit `C-P`, I get an autocomplete based on other words in the file, but no documentation lookup.

**Comment by ccorcos** [comment]
I have these two plugins installed as well, which I believe should make it work.

```
Plugin 'tpope/vim-fireplace' " clojure repl support
Plugin 'tpope/vim-classpath.git' " for looking up java objects for closure fireplace
```

Am I missing some other configurations that show the dropdown?

**Comment by tpope** [comment]
`:h compl-omni`
