### ISSUE TITLE
pretty print results

### ISSUE THREAD

**Issue by mgrubb** [tpope/vim-fireplace#262]
It would be nice to be able to either set an option or get separate keybinds for cpp and c!! to use pretty printed format.  This would make using clojure code to refactor existing code nicer.

**Comment by tpope** [comment]
Doesn't cider-nrepl have some sort of support for this? Can we tap into it?

**Comment by mgrubb** [comment]
There is a `cider.nrepl.middleware.pprint/wrap-pprint` middleware that will return a `:pprint-out` key in the response if the the `:eval` message is sent with the `:pprint` key set to `1`.
See 
https://github.com/clojure-emacs/cider-nrepl#supplied-nrepl-middleware
https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/pprint.clj#L99

**Comment by tpope** [comment]
I think it would be fine to make this the default behavior for `cpp`. Maybe `c!!` too if you can get the indenting correct.

**Comment by devth** [comment]
@mgrubb did you ever impl anything on this? pprint would be awesome.

**Comment by Deraen** [comment]
This has been implemented and can be closed.
