### ISSUE TITLE
Interaction with vim-projectionist: Can't open new buffer while a REPL is open

### ISSUE THREAD

**Issue by j-po** [tpope/vim-fireplace#265]
```
Error detected while processing function <SNR>14_projectionist_detect[4]..<SNR>14_path[1]..<SNR>14_connect[10]..fireplace#register_port_file[9]..fireplace#nrepl_connection#open[13]..fireplace#nrepl#for[3]..<SNR>58_nrepl_process[1]..<SNR>58_nrepl_message[3]..<SNR>58_nrepl_
call[3]..<SNR>55_nrepl_transport_call[2]..<SNR>55_nrepl_transport_dispatch:
line    3:
E121: Undefined variable: out
E15: Invalid expression: out
```
All of my settings are pretty much straight out of the box, but I'd be happy to share things that might be salient.

**Comment by tpope** [comment]
That stacktrace points at https://github.com/tpope/vim-fireplace/blob/600e64dbad928fb864bbee5eb73a0f7dae68e439/autoload/fireplace/nrepl_connection.vim#L100 in the latest version, which doesn't line up.

**Comment by j-po** [comment]
Huh, that's weird. My versions of fireplace and projectionist are both current with master.

**Comment by j-po** [comment]
Seems to still present without projectionist (and fireplace pulled an hour ago):
```
Error detected while processing function <SNR>13_path[1]..<SNR>13_connect[10]..fireplace#register_port_file[9]..fireplace#nrepl_connection#open[13]..fireplace#nrepl#for[3]..<SNR>45_nrepl_process[1]..<SNR>45_nrepl_message[3]..<SNR>45_nrepl_call[3]..<SNR>42_nrepl_transport_
call[2]..<SNR>42_nrepl_transport_dispatch:
line    3:
E121: Undefined variable: out
E15: Invalid expression: out
```

**Comment by j-po** [comment]
Updating neovim's python host seems to have fixed it. (Also, I apologize for earlier saying that my setup was pretty much straight out of the box but somehow neglecting to mention that I was using neovim, which was probably salient as hell.)
