### ISSUE TITLE
Error during Require

### ISSUE THREAD

**Issue by dragosboca** [tpope/vim-fireplace#269]
If I try to use :Require to reload the current file, the following error is shown

(require 'dispatcher.routes :reload-all)  
Error detected while processing function <SNR>131_Require[13]..fireplace#client[2]..fireplace#platform[9]..fireplace#register_port_file[9]..fireplace#nrepl_connection#open[13]..fireplace#nrepl#for:  
line   14:  
E15: Invalid expression: \" nil]  
E15: Invalid expression: \" nil]  
Press ENTER or type command to continue

**Comment by tpope** [comment]
I can't find the issue, but I fixed another `" nil]` error, so I believe this is taken care of.
