### ISSUE TITLE
Support for testing

### ISSUE THREAD

**Issue by gerardc** [tpope/vim-fireplace#27]
Would it be possible to integrate testing similar to the `:Rake` command in vim-rails? 

The development cycle outlined by Gareth Jones for emacs is pretty sweet http://blog.gaz-jones.com/2012/02/02/clojure_development_cycle.html

**Comment by devth** [comment]
I've been playing with Midje.

Using this to get by:

```viml
autocmd FileType clojure nmap <buffer> ctm :Eval (require 'midje.repl)(midje.repl/load-facts *ns*)<cr>
```
