### ISSUE TITLE
Forward slash should probably cound as word boundary

### ISSUE THREAD

**Issue by not-raspberry** [tpope/vim-fireplace#273]
The problem:

1. I have some code like: `(string/replace "abcd" "a" "A")`
2. The cursor is at the first s, in normal mode.
3. I press w. I expect the cursor to jump to the slash or the "r" character (
both would be fine).
4. It jumps to the `"` instead.

I find that almost always I want to jump within the namespaced symbol, not over it. When I want to jump to the next argument, there's always W.

What are the opinions of other users?

I don't know much about vim configuration but it seems to be defined around there https://github.com/tpope/vim-fireplace/blob/49d3aca64df0ee6ea529c08850fb42344407bcd3/plugin/fireplace.vim#L1418. However, modifying that regex did not solve the problem.

**Comment by not-raspberry** [comment]
Same goes for the dot character.

**Comment by tpope** [comment]
Fireplace has its own internal definition but that's completely independent of `w`.
