### ISSUE TITLE
Is there a way to run fireplace commands when in non-Clojure files?

### ISSUE THREAD

**Issue by rsslldnphy** [tpope/vim-fireplace#277]
For example, when editing a migration (.sql) file, I often want to run `:Eval (user/migrate)` and `:Eval (user/rollback)`, but the `:Eval` command isn't available in SQL files. Is there an easy way to make it available or would that require changing the plugin itself?

**Comment by tpope** [comment]
Unfortunately a lot of behavior is tied to the buffer (namespace to run in for instance), so that's not an easy change to make.

**Comment by exupero** [comment]
There's a nREPL Python client that you can call from vimscript. I've used it to run nREPL commands from arbitrary files.
