### ISSUE TITLE
CLJC: is there a way to select server or client when using quasi-repl commands?

### ISSUE THREAD

**Issue by altV** [tpope/vim-fireplace#289]
0. thank you for this awesome plugin

I am using cljc now, and before that I had cljs files eval connected to browser via figwheel, and clj connected to server.

I might be missing if it's an easy or hard, but can I somehow made another set of bindings, or make some multiplexing `nmaps` before I eval a command?

If it's not currently possible via some mappings, can you please point to how one could approach such thing?

(Basically, you open CLJC buffer, hit F2, then eval your forms straight to browser, then hit F1, and evalling them against server, as an example.)

**Comment by devth** [comment]
I'm also interested in this exact issue.

Perhaps a flag to `:Connect` to tell it which to prefer by default and a way to switch like @altV is suggesting?

**Comment by tpope** [comment]
I've made cljc files use the ClojureScript repl if available and plain Clojure if not. And I've added a `b:fireplace_clc_platform` variable for if you want to rig up some sort of toggle.
