### ISSUE TITLE
Support python3 in vim 

### ISSUE THREAD

**Issue by wyegelwel** [tpope/vim-fireplace#290]
This is more of a heads up then anything else. 

I installed a recent version of Ubuntu (16.10, though apparently 16.04 also has this) and the default vim (sudo apt-get install vim) doesn't come compiled with python support, only python3. This was causing serious problems with the experience of fireplace (evals were hanging). I followed the recommendation on this page to get "python" support instead. http://askubuntu.com/questions/775059/vim-python-support-on-ubuntu-16-04 Now things are working fine.

**Comment by tpope** [comment]
My strategy around this has been to try to support both Python 2 and 3, though I guess I only tested the external execution code path. Fixing it might be as simple as updating the `has('python')` checks to allow for Python 3.

**Comment by tpope** [comment]
`:python3` is now supported.
