### ISSUE TITLE
Auto-update :Last buffer

### ISSUE THREAD

**Issue by jeaye** [tpope/vim-fireplace#297]
You had mentioned in https://github.com/tpope/vim-fireplace/issues/242 that you were considering this feature; I think it would be superb and would allow for a pretty handy workflow, especially when dealing with non-trivial data structures (such as big/nested maps).

Is this still something you'd consider?

**Comment by tpope** [comment]
I'm open to it but don't see myself implementing it.

**Comment by jeaye** [comment]
Word. We can leave this open, as a feature request awaiting a hero, then, or do with it as you will. Thank you!

**Comment by lxsli** [comment]
Similar to #81

**Comment by tpope** [comment]
I think what I wanna do here is replace the `:Last` buffer with a cumulative log of previous executions. Then eval operations can update asynchronously update the buffer if the window is open.
