### ISSUE TITLE
Cider-based formatexpr should be opt-in

### ISSUE THREAD

**Issue by devth** [tpope/vim-fireplace#298]
My `gq` was hosed after upgrading because I don't use Cider. Maybe it should be an opt-in feature?

Even after I configured Cider the result wasn't satisfactory because Cider's formatting doesn't respect the `formatoptions` that I rely on.

**Comment by tpope** [comment]
My thinking was one could use `gw` to get the native reformat and `gq` to get the Cider version.

**Comment by devth** [comment]
I didn't even know `gw` was a thing 😫 
Goes to show how much I know about vim and life in general.
