### ISSUE TITLE
Recent commit broke cpp

### ISSUE THREAD

**Issue by SevereOverfl0w** [tpope/vim-fireplace#300]
https://github.com/tpope/vim-fireplace/commit/4d2d29a73fd4f0f54c06da44d3e2f9639435cda9 seems to have broken cpp for me. I think it inserts something from the clipboard.

I'm guessing that the `cp` mapping has generally broken with that commit.

**Comment by tpope** [comment]
Looks like I broke *all* maps, in a very noisy way, by failing to stage a very important line. Latest push should fix that. Can you check if things are now working for you?

**Comment by SevereOverfl0w** [comment]
Works again :tada:
