### ISSUE TITLE
Provide tag stack support with CTRL-] / CTRL-T maps

### ISSUE THREAD

**Issue by t0il3ts0ap** [tpope/vim-fireplace#304]
> [\<C-D\> jumps to the definition of a symbol (even if it's inside a jar file).

How to override above with  **<ctrl-]>**

Personally, I think **<ctrl-]>** should be default goto definition key, as the tag file generation is not required anymore with vim-fireplace.

This behavior is practiced by [fatih/vim-go](https://github.com/fatih/vim-go) as well.

**Comment by t0il3ts0ap** [comment]
`nnoremap <C-]> :execute 'Djump' expand('<cword>') <CR>`

Found an ugly way to do it.

**Comment by tpope** [comment]
I think providing `<C-]>` would be cool but only if we also support its companion `<C-T>`, i.e. implement a tag stack.

Slightly cleaner override in the meantime:

    autocmd FileType clojure nmap <C-]> ]<C-D>

**Comment by jrdoane** [comment]
I know that this was suggested a while ago, but this still would be a huge benefit.
