### ISSUE TITLE
set wildignore+=*/tmp/*  in vimrc causes "no live REPL connection"

### ISSUE THREAD

**Issue by dset0x** [tpope/vim-fireplace#307]
Hello,

After spending some time trying to figure out why the automatic repl connection wasn't working for me, it turned out that having `set wildignore+=*/tmp/*` in my vimrc was what was causing it. I'm not quite sure why this is a problem, or if it is a bug (editing wildignore might not be the best idea), but at the very least it might help someone else who might have a similar configuration.

```
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()
Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-classpath'
Plugin 'tpope/vim-fireplace'

set nocompatible

filetype plugin indent on
syntax on

set wildignore+=*/tmp/*
```

Commenting the last line out fixes fireplace for me.

**Comment by tpope** [comment]
Wild ignore affects like a million different Vim behaviors, and putting a directory in it can break all kinds of things. Thanks for reporting, but I'm washing my hands of the matter.
