### ISSUE TITLE
Doc with invalid namespace

### ISSUE THREAD

**Issue by Herz3h** [tpope/vim-fireplace#314]
Hello,

I'm currently editing a file thats on a remote server, this clojure file requires a namespace which I don't have access to locally. So whenever I try to use Doc on a keyword it fails because it couldn't load the namespace.

Not sure if this is a normal behavior (not that familiar with repl/clojure), but should Fireplace require the namespace for Doc to work (in case of seeking doc for the language keywords) ?

**Comment by tpope** [comment]
Does "editing a file on a remote server" mean something like a `ssh://` URL or something else?

**Comment by tpope** [comment]
So Fireplace does issue a `(require 'namespace)` when calling `:Doc` from a file with a `(ns 'namespace)` declaration. I can offer further advice debugging but I think this is an environment issue not a Fireplace bug.
