### ISSUE TITLE
Override `gd`

### ISSUE THREAD

**Issue by positron** [tpope/vim-fireplace#319]
Since the README says you favor enhancing built-ins, I was expecting `gd` to go to definition like `gf`  goes to a namespace. Why is go to definition bound to `<C-[>d`?

In the meantime I overrode it with

    autocmd FileType clojure nmap gd ]<C-D>

Thanks for the awesome plugin!

**Comment by tpope** [comment]
`gd` is for local variables.

```
gd			Goto local Declaration.  When the cursor is on a local
			variable, this command will jump to its declaration.
```

The built-in behavior works (sort of) for Clojure, so I didn't want to override it.

**Comment by positron** [comment]
Ah, I figured I was missing something like that.
