### ISSUE TITLE
Autocomplete for ClojureScript

### ISSUE THREAD

**Issue by juan-sebastian** [tpope/vim-fireplace#320]
Hi I'm quite new to Clojure/ClojureScript I'm having an issue with the autocompletion in ClojureScript, for example when I write `de` then `^X^O` to trigger the autocompletion a got nothing but when I do `clojure.core/de` then `^X^O` then I have all the results, I'm missing something?

PS: I set up my repl with the instructions found here (https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-with-Vim) and fireplace is property connected to the nrelp.

**Comment by bbatsov** [comment]
I'm assuming the completion should work in the presence of `cider-nrepl`, as it provides autocompletion for ClojureScript.

**Comment by tpope** [comment]
This is working fine on master with cider-nrepl installed. Let me know if it's still an issue.

**Comment by juan-sebastian** [comment]
Hi sorry for the delay, yes it is working fine now :-)
