### ISSUE TITLE
[question] How to bring up a prompt with the last evaluated form

### ISSUE THREAD

**Issue by jlesquembre** [tpope/vim-fireplace#321]
I'm trying to create a custom map to open a prompt pre-populated with the latest previous evaluated form. Basically `cqp` with the last from. Is it possible?

**Comment by tpope** [comment]
Something like `cqp<Up>` ought to do it.

**Comment by jlesquembre** [comment]
Yes, thanks, that seems to work, but only for forms evaluated from the command line window, forms evaluated with `cpp` are not shown

**Comment by tpope** [comment]
Forms evaluated with `cpp` typically contain newlines, this isn't compatible with the current `cqp` implementation as it stands.
