### ISSUE TITLE
The "cqq" repl breaks after :NoMatchParen.

### ISSUE THREAD

**Issue by markx** [tpope/vim-fireplace#334]
I run command `:NoMatchParen` in the `cqq` repl window, and then the repl shows error when I hit `enter` on a form.

```
Error detected while processing function <SNR>25_editop[2]..<SNR>25_input[8]..<SNR>25_actually_input[1]..<SNR>16_NoMatchParen:
line    2:
E11: Invalid in command-line window; <CR> executes, CTRL-C quits:   noau windo silent! call matchdelete(3)
Press ENTER or type command to continue
```

Normally I wouldn't run `:NoMatchParen` in the repl window anyway, 
but I do have `autocmd FileType clojure NoMatchParen` in my vimrc.

**Comment by tpope** [comment]
The repl window is just a variant of the window that pops up if you press `q:` or `q/`, and `:NoMatchParen` doesn't work there either. You'll need to add a `if` or a `silent!` to your autocommand.
