### ISSUE TITLE
Not able to jump to source when namespace alias is used

### ISSUE THREAD

**Issue by sushovannits** [tpope/vim-fireplace#342]
The jump to source [C-d does not work when namespace alias is used as below:

```
(ns test.api.core
  (:require [liberator.core as liberator]))
(liberator/defresource ...)
 |----> Cursor here and [C-d is pressed
```
 
Is it not possible or am I missing something in setup?

Thanks

**Comment by tpope** [comment]
That should work, assuming you required the current file. I don't suppose it's giving a useful error message?

**Comment by sushovannits** [comment]
Thanks for the response. Well figured out there was failure when doing:%Eval and that was due to a wrong jdk version (wrong as incompatible with a dependency). It is working now.

**Comment by sushovannits** [comment]
Hi @tpope Apologies for commenting on a closed issue but not sure if a new one has to be opened. The thing is it is again not working for me:
For example; while running this vim command `Source <some-namspace-alias>/<some-symbol>` works, a [Cd or [d gives a "Definition not found" or "Source not found". I am not sure how to debug this even. Some help would be great.

**Comment by tpope** [comment]
Are those the exact error messages?

**Comment by sushovannits** [comment]
> Are those the exact error messages?

The exact message for [Cd is: 
- `Couldn't find source for <some-namspace-alias>` when the cursor is over `<some-namespace-alias>`.
- `Couldn't find source for <some-symbol>` when the cursor is over `<some-symbol>`

And for [d it just says `Source not found`

Whereas
`Source <some-namspace-alias>/<some-symbol>` works fine. Please let me know if anything else will help.

**Comment by sushovannits** [comment]
Well the culprit was:
```
set iskeyword-=/
```
in my ~/.vim_runtime/my_plugins/vim/after/ftplugin/clojure.vim
I put it in there because for searching with the key mapping *

**Comment by sushovannits** [comment]
@tpope Anyway to use special word boundary for fireplace

**Comment by tpope** [comment]
Something like #370 would work.
