### ISSUE TITLE
Undefined variable: v:none

### ISSUE THREAD

**Issue by anmonteiro** [tpope/vim-fireplace#352]
Seems like https://github.com/tpope/vim-fireplace/commit/5aed1bc834456a5517221ba82f57d2577e8c932c is erroring out for me on latest Neovim with:

```
Vim(elseif):E121: Undefined variable: v:none
```

Any additional info I can provide?

**Comment by SevereOverfl0w** [comment]
there is no v:none in neovim.

**Comment by SevereOverfl0w** [comment]
https://github.com/neovim/neovim/issues/9770#issuecomment-475203341 should be v:null apparently?

**Comment by tpope** [comment]
🙄🙄🙄
