### ISSUE TITLE
Omnicomplete issues as of recently

### ISSUE THREAD

**Issue by anmonteiro** [tpope/vim-fireplace#353]
Can't exactly pinpoint when, but sometime since last week omnicomplete has been a little broken for me. Any call to it will first produce:

```
E745: Using a List as a Number                                                                                                                                 
Back at original
Press ENTER or type command to continue
```

And once I dismiss this message it'll return completions that are not context aware (e.g. trying to complete `clojure.string/|` where `|` is cursor returns the functions in `clojure.core`).

**Comment by tpope** [comment]
What cider-nrepl version are you using?

**Comment by anmonteiro** [comment]
We're on 0.22 beta5

**Comment by tpope** [comment]
Neovim? If so, does it work on plain Vim?

**Comment by anmonteiro** [comment]
Oh yeah this is Neovim. I might not know how to test the exact setup in Vim.

**Comment by anmonteiro** [comment]
Thanks for the fix. I've confirmed it works.

**Comment by SevereOverfl0w** [comment]
https://github.com/neovim/neovim/issues/10604#issuecomment-515420364 this looks like it was missed because it was fixed in vim 8 series.
