### ISSUE TITLE
Filtering :Stacktrace

### ISSUE THREAD

**Issue by tpope** [tpope/vim-fireplace#362]
Switching from passive location list stacktrace retrieval to an active `:Stacktrace` command means we now have an opportunity to pass parameters, like `:Stacktrace +dups -java`. The first step is to switch back to the nREPL stacktrace op from the custom eval we're currently using.

**Comment by SevereOverfl0w** [comment]
In replant I delegate filter to vim-qf and append # into the end of lines.
