### ISSUE TITLE
Make pprint width configurable

### ISSUE THREAD

**Issue by SevereOverfl0w** [tpope/vim-fireplace#364]
Currently appears to be tied to `&columns`. I find &columns too wide when I am working with lists of maps, I'd rather constrain the pprint to ~80-120 chars or so.

e.g.

```
({:a 10, :children [{:a 20, :children [:a :b :c]} {:a 30, :children [:a :b :c]}]} {:a 20, :children [:a :b :c]} {:a 30, :children [:a :b :c]})
```

is harder to read than

```
({:a 10, :children [{:a 20, :children [:a :b :c]} {:a 30, :children [:a :b :c]}]}    
 {:a 20, :children [:a :b :c]}                                                       
 {:a 30, :children [:a :b :c]})  
```

(the latter was done by reducing the width of my window by opening an adjacent terminal)

**Comment by tpope** [comment]
I'd accept a patch that does `min([old_value, get(g:, 'fireplace_print_width', 9999)])`.
