### ISSUE TITLE
.nrepl-port not found after 6e7da6c06e9562403dc760e14f57262f0f2b2098

### ISSUE THREAD

**Issue by sorsasampo** [tpope/vim-fireplace#367]
I'm starting `vim` above a directory that contains the `.nrepl-port` file, and with current master (8712a16) that detection does not work. If I reset to `6e7da6c^`, it works again.

I think 6e7da6c06e9562403dc760e14f57262f0f2b2098 may be the culprit.

**Comment by tpope** [comment]
That's a good guess. Did you verify that it fails on that commit and works on the ancestor?

**Comment by sorsasampo** [comment]
@tpope: yes, d7d3440d69aa8b5bcb0d8a6d6c2584a1b582ef92 is good, 6e7da6c06e9562403dc760e14f57262f0f2b2098 is bad.
