### ISSUE TITLE
Fireplace: no default ClojureScript REPL

### ISSUE THREAD

**Issue by lamartire** [tpope/vim-fireplace#372]
Hello!
I'm trying to connect to any repl with `:FireplaceConnect` and then trying to format `cljs` code with `:Cljfmt` and see this error `Fireplace: no default ClojureScript REPL`. 
Whats wrong? How I can solve this error and format `cljs` code?
Also, I have not any problems with `clj` code.

**Comment by tpope** [comment]
This is addressed in the docs. Sometimes it's easier than said than done but I don't have the bandwidth to provide tech support for it.

**Comment by marvinthepa** [comment]
This is the documentation that helped me when searching for this error message: https://figwheel.org/docs/vim.html
(I do not mean to imply that the fireplace docs are insufficient. Tim, you rock! 🚀 )

**Comment by robbieh** [comment]
For all the other poor souls who Google sends here:
https://gist.github.com/finalfantasia/292b8432dc0072b2397ea4d694aab930

The trick is to do this after you connect:
```
:CljEval (shadow/repl :your_build_id_here)
```

**Comment by chr15m** [comment]
If you're using a non-shadow ClojureScript environment/interpreter such as [`nbb`](https://github.com/babashka/nbb) you can get into the right mode with the magic incantation:

```
:CljEval (ns cljs.user)
```

This works because Fireplace listens out for this namespace to then set the default ClojureScript repl.
