### ISSUE TITLE
Use of private var in preload

### ISSUE THREAD

**Issue by chopptimus** [tpope/vim-fireplace#375]
I've been using Fireplace with [babashka](https://github.com/borkdude/babashka/), which works pretty much out the box with the exception of `s:repl.preload` which uses a private var in `clojure.core` to load libs. Babashka for whatever reason can't access the private vars using the var reader literal like the canonical Clojure implementation can. Replacing the call to `#'clojure.core/load-one` with `clojure.core/require` seemed to fix the issue with Babashka and didn't break regular Clojure _as far as I can tell_. There may well be a very good reason that `load-one` was used that I'm not aware of.

**Comment by tpope** [comment]
https://github.com/tpope/vim-fireplace/issues/161#issuecomment-46070857 Is the reason for `load-one`. I'm not sure what to do about this. I'd be curious to dig into the "for whatever reason" part, maybe there's a workaround on that end.

**Comment by chopptimus** [comment]
So the reason it can't access that var is that it doesn't exist, not because it's private, probably because Babashka is compiled with GraalVM and so doesn't support dynamic class loading.

**Comment by chopptimus** [comment]
Just falling back to require if `load-one` isn't available seems to do the trick.
 ```(let [ns-sym sym
      load-one-var (clojure.core/resolve (quote clojure.core/load-one))]
  (clojure.core/when-not (clojure.core/find-ns ns-sym)
    (try
      (if load-one-var
        (load-one-var ns-sym true true)
        (clojure.core/require ns-sym))
      (catch Exception e
        (clojure.core/when-not (clojure.core/find-ns ns-sym) (throw e))))))
```
