### ISSUE TITLE
Omnicomplete fails

### ISSUE THREAD

**Issue by robbieh** [tpope/vim-fireplace#377]
I'm not an emacs user, but I'm 93% sure I have cider installed. The `package-activated-list` says `(cider clojure-mode evil goto-chg hy-mode monroe parseedn parseclj a pkg-info epl queue seq sesman spinner undo-tree)` so that looks pretty good, right?

But in classic Vim version 8.0.1453, the omincomplete function gives this error: 
`E605: Exception not caught: Fireplace: no 'complete' nREPL op available (is cider-nrepl installed?)`

Maybe I don't understand what the install guide is trying to tell me? https://docs.cider.mx/cider/basics/installation.html

**Comment by tpope** [comment]
You don't need cider installed, you need cider-nrepl installed. Separate but related project.
