### ISSUE TITLE
f633ed9 stopped working with shadow-cljs

### ISSUE THREAD

**Issue by tim-smart** [tpope/vim-fireplace#378]
```
$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
```

Before this commit `:CljEval (shadow/repl :app)` was working great.

After this commit it seems I can run `:CljEval` commands, but `:CljsEval` says there is no default ClojureScript repl.

If you need any more information just let me know :)

**Comment by tpope** [comment]
What is `shadow` aliased to?

If you can link to an example app that I can reproduce the problem on, that would help a lot.

**Comment by tim-smart** [comment]
```clj
(:require [shadow.cljs.devtools.api :as shadow])
```

I'll see if I can create a test project soon.

Also, for some reason I have to Ctrl-C after evaluating code. Is it taking over stdin or something?

**Comment by tpope** [comment]
Huge pain both to diagnose and to fix but it should be working now. Please report back on whether it works.
