### ISSUE TITLE
no live REPL connection

### ISSUE THREAD

**Issue by DmitryAndreyeff** [tpope/vim-fireplace#381]
Hi!
I need to connect to a REPL server on a different host. :FireplaceConnect works without errors, but after that I get "Fireplace: no live REPL connection" on any attempt to evaluate something. To exclude network problems, in parallel I test nrepl connection to the same endpoint with another client (nrepl-python-client) and it is stable. Thanks in advance!

Edit: Those are actually two containers (containerized VIM and Clojure) that I'm trying to get working together in Docker on Windows 10 desktop. When I'm running the same two containers on Ubuntu host, this setup works. Any suggestions are welcome. I would be really happy to get it working.

**Comment by tpope** [comment]
How are you answering the `Scope connection to:` prompt?

**Comment by DmitryAndreyeff** [comment]
I was just approving the "/" suggestion, my assumption was that it is not important when I evaluate simple (+ 2 2) expressions. Now I mounted a host directory to the same path in both containers, set it as working dir for lein and for vim, and it seems to work! Many thanks!
