### ISSUE TITLE
CQP - support autocomplete

### ISSUE THREAD

**Issue by danlinenberg** [tpope/vim-fireplace#386]
Hi,

Is there a way of support autocomplete when using CQP macro? or is there a workaround for it?

Thanks.

**Comment by tpope** [comment]
Basic tab completion works. If you want full blown omnicomplete, use `cqc`.

**Comment by danlinenberg** [comment]
Any reason why tab complete wouldn't work for me?

**Comment by tpope** [comment]
If omnicomplete works, then `cqp` tab completion should work. Tab completion swallows errors because there's no good way to display them, so if you're having trouble, try the omnicomplete.
