### ISSUE TITLE
Stacktrace not showing on lopen

### ISSUE THREAD

**Issue by zendevil** [tpope/vim-fireplace#389]
I evaluate some code that contains an exception and the exception partially shows up at the smaller buffer that shows up at the bottom, but upon doing lopen that exception isn't in the list. How do I see the full stack trace?

**Comment by tpope** [comment]
Do you have cider-nrepl installed and set up?

**Comment by zendevil** [comment]
I do have [cider/cider-nrepl "0.26.0"] in my {:project/dev {:plugins []}} in project.clj and nrepl .0.8.13 in :dependencies. Is there something else that I need to install too?

**Comment by tpope** [comment]
That should be enough, but check `:echo fireplace#client().transport.describe.aux['cider-version']` to make sure it loaded correctly.

**Comment by tpope** [comment]
Actually scratch all that. You need to call `:Stacktrace` to get the stacktrace. The automatic location list got removed quite a while back.

**Comment by zendevil** [comment]
Yes it does give a stacktrace with :Stacktrace, but it seems that this doesn't show the full stack trace and doesn't show which expection was raised (there's no "caused by"). Is there a way to see the full stack trace? For example cider in emacs shows a more detailed stack trace than fireplace?

**Comment by tpope** [comment]
Use `:Stacktrace!`. This is all [documented](https://github.com/tpope/vim-fireplace/blob/07b0256b08e0da6d31200663cbe6d6f8c995a287/doc/fireplace.txt#L233-L238).

**Comment by zendevil** [comment]
Also, for some reason when I wrap a standalone expression in prn and evaluate that, its value doesn't print in the repl. Is there a way to see its value?
