### ISSUE TITLE
.RunTests unable to find aliased deftest

### ISSUE THREAD

**Issue by mbutlerw** [tpope/vim-fireplace#403]
Hi, 

Invoking RunTests as `:.RunTests` within an aliased deftest appears to go and find the previous unaliased `def/defn/deftest` and passes that to `clojure.test/test-vars`, rather than the deftest you are within.

```
(ns foo-test
  (:require [clojure.test :as t :refer [deftest]]))

(deftest refered-test
  (t/is true))

(defn foo [] inc)

(def bar 1)

(t/deftest aliased-test
  (t/is false))
  
;; Calling :.RunTests while inside aliased-test
;; => (clojure.test/test-vars [#'foo-test/bar])
```

Apologies if this is a misunderstanding on my part, and thanks for all your work on fireplace :+1:

**Comment by frenchy64** [comment]
Metadata for test selectors also seems to defeat `.RunTests`.

```clojure
(deftest ^:integration my-test
  ...)

**Comment by frenchy64** [comment]
I can confirm both issues are fixed, thanks!
