### ISSUE TITLE
Unable to jump to source in recent vim version

### ISSUE THREAD

**Issue by shrekwang** [tpope/vim-fireplace#414]
Fireplace used to work fine on my local settings.  After I upgraded my Macvim to  Release 176(Vim 9.0.1276)  ,  I find fireplace can't jump to source location anymore.  After some digging around , I believe the problem may related to vim zip plugin.  There is an issue about this : https://github.com/vim/vim/issues/8974. 

To verify the problem, 
```vim
"worked, open the zip entry successfully
:edit zipfile:///${my-homedir}/.m2/repository/cheshire/cheshire/5.11.0/cheshire-5.11.0.jar::cheshire/core.clj

"not worked, open a blank buffer
:edit zipfile:/${my-homedir}/.m2/repository/cheshire/cheshire/5.11.0/cheshire-5.11.0.jar::cheshire/core.clj
```

**Comment by tpope** [comment]
Are you sure Fireplace is updated? This was fixed in #397.

If it's happening on the latest Fireplace, report back with the value of `:echo g:loaded_zipPlugin`.
