### ISSUE TITLE
Run corresponding tests?

### ISSUE THREAD

**Issue by hoclun-rigsep** [tpope/vim-fireplace#419]
Looks like a common project layout has 

```tree
src
└── myproj
    └── CD30.clj
test
└── myproj
    └── CD30_test.clj
```

Would it be good if there were a map to run tests in CD30-test from the CD30 buffer, or am I missing something? This is actually how I thought `cpr` worked when I started looking into writing tests.

**Comment by tpope** [comment]
Fireplace doesn't attempt to understand your directory structure. https://github.com/tpope/vim-salve does some stuff along those lines.
